Repository chingu-voyages/v39-bears-team-11, pull requests merged in 2022-04, with the labels that each got.

#31 Refactor/readme
  README.md
  assets/desktop_mockup.png
  assets/mobile_mockup.png
Labels: documentation

#32 Initialize App
  client/.gitignore
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/reportWebVitals.js
  client/src/setupTests.js
  client/yarn.lock
  server/.gitignore
  server/app.js
  server/package-lock.json
  server/package.json
Labels: task, must_have, user_story

#68 Chore/create folder structure
  client/src/App.js
  client/src/components/button/Button.js
  client/src/components/button/Button.test.js
  client/src/index.css
  client/src/store/store.js
  client/src/styles/App.module.css
  client/src/styles/Button.module.css
  client/src/test/Component.test.js
  client/src/utilities/config.js
  client/src/utilities/helper.js
Labels: task, must_have

#94 Setup/add basic styles
  client/src/index.css
  client/src/utils/config.js
  client/src/utils/helper.js
Labels: task

#96 Add airbnb eslint configuration to react app
  client/.eslintignore
  client/.eslintrc
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/App.test.js
  client/src/components/button/Button.js
  client/src/index.js
  client/src/setupTests.js
  client/src/store/store.js
  client/src/test/Component.test.js
  client/src/utils/config.js
  client/src/utils/helper.js
  client/yarn.lock
Labels: task

#98 Import icons from figma
  client/src/icons/chat-room/chatroom-camera-icon.png
  client/src/icons/chat-room/chatroom-send-icon.png
  client/src/icons/chats/chats-cta-icon.png
  client/src/icons/logo/litetalk-logo-icon.svg
  client/src/icons/navbar/navbar-chats-icon.svg
  client/src/icons/navbar/navbar-friends-icon.svg
  client/src/icons/navbar/navbar-search-icon.svg
  client/src/icons/profile/profile-delete-icon.svg
  client/src/icons/profile/profile-edit-icon.svg
  client/src/icons/profile/profile-logout-icon.svg
  client/src/icons/profile/profile-picture-update-icon.svg
  client/src/icons/profile/profile-user-icon.svg
  client/src/icons/searchbox/searchbox-search-icon.png
  client/src/icons/signup/signup-email-icon.png
  client/src/icons/signup/signup-illustration.png
  client/src/icons/signup/signup-password-icon.png
  client/src/icons/signup/signup-user-icon.png
Labels: task

#100 Feature/style main components
  client/.eslintrc
  client/package-lock.json
  client/src/App.js
  client/src/components/chatroom/ChatRoom.js
  client/src/components/chatroom/ChatRoom.test.js
  client/src/components/chats/Chats.js
  client/src/components/chats/Chats.test.js
  client/src/components/friends/Friends.js
  client/src/components/friends/Friends.test.js
  client/src/components/profile/Profile.js
  client/src/components/profile/Profile.test.js
  client/src/components/search/Search.js
  client/src/components/search/Search.test.js
  client/src/components/signup/Signup.js
  client/src/components/signup/Signup.test.js
  client/src/index.css
  client/src/index.js
  client/yarn.lock
  server/utils/config.js
  server/utils/logger.js
Labels: task

#103 Feature/style header
  client/src/components/logo/Logo.js
  client/src/components/logo/Logo.test.js
  client/src/components/navbar/Navbar.js
  client/src/components/navbar/Navbar.test.js
  client/src/components/navlinks/NavLinks.js
  client/src/components/search/Search.js
  client/src/components/user/User.js
  client/src/icons/logo/litetalk-logo-name.svg
  client/src/icons/navbar/navbar-chats-icon.svg
  client/src/icons/navbar/navbar-friends-icon.svg
  client/src/icons/navbar/navbar-search-icon.svg
  client/src/index.css
  client/src/styles/Logo.module.css
  client/src/styles/Navbar.module.css
  client/src/styles/User.module.css
Labels: task

#109 Feature/add footer
  client/.eslintrc
  client/src/components/footer/Footer.js
  client/src/styles/Footer.module.css
Labels: task
