Repository chingu-voyages/v39-bears-team-11, pull requests merged in 2022-05, with the labels that each got.

#111 Feature/messages router
  server/Controller/messageController.js
  server/app.js
  server/models/message.js
  server/models/user.js
  server/routes/messageRouter.js
  server/utils/helper.js
  server/utils/middleware.js
Labels: enhancement, task, must_have

#112 Feature/add search
  client/.eslintrc
  client/data/MOCK_DATA.json
  client/package-lock.json
  client/package.json
  client/services/people.js
  client/src/App.js
  client/src/components/button/AddFriendButton.js
  client/src/components/button/Button.js
  client/src/components/button/CancelButton.js
  client/src/components/button/ConfirmButton.js
  client/src/components/button/UnfriendButton.js
  client/src/components/container_heading/ContainerHeading.js
  client/src/components/friend_tag/FriendTag.js
  client/src/components/main_page/MainPage.js
  client/src/components/modal/Modal.js
  client/src/components/navbar/Navbar.js
  client/src/components/navbarlink/NavbarLink.js
  client/src/components/navbarlinks/NavbarLinks.js
  client/src/components/search/Search.js
  client/src/components/search_result/SearchResult.js
  client/src/components/search_results/SearchResults.js
  client/src/components/searchbox/SearchBox.js
  client/src/components/signup/Signup.js
  client/src/components/user/User.js
  client/src/icons/profile-picture-man-unsplash.jpg
  client/src/icons/profile-picture-woman-unsplash.jpg
  client/src/icons/profile/profile-logout-icon.svg
  client/src/icons/profile/profile-user-icon.svg
  client/src/index.css
  client/src/store/features/users/usersSlice.js
  client/src/store/store.js
  client/src/styles/Button.module.css
  client/src/styles/ContainerHeading.module.css
  client/src/styles/Footer.module.css
  client/src/styles/FriendTag.module.css
  client/src/styles/Modal.module.css
  client/src/styles/Navbar.module.css
  client/src/styles/SearchBox.module.css
  client/src/styles/SearchResults.module.css
  client/src/styles/User.module.css
  client/yarn.lock
Labels: task

#113 Refactor/router
  client/src/App.js
  client/src/components/chatroom/ChatRoom.js
  client/src/components/chats/Chats.js
  client/src/components/friends/Friends.js
  client/src/components/main_page/MainPage.js
  client/src/components/profile/Profile.js
  client/src/components/search/Search.js
  client/src/components/search_result/SearchResult.js
Labels: enhancement

#114 Feature/add friends
  client/src/components/button/ConfirmButton.js
  client/src/components/button/UnfriendButton.js
  client/src/components/friends/Friends.js
  client/src/components/modal/Modal.js
  client/src/components/search/Search.js
  client/src/components/search_result/SearchResult.js
  client/src/components/search_results/SearchResults.js
  client/src/components/searchbox/SearchBox.js
  client/src/index.css
  client/src/store/features/users/usersSlice.js
  client/src/styles/Button.module.css
  client/src/styles/ContainerHeading.module.css
  client/src/styles/SearchResults.module.css
Labels: task

#117 Feature/profile page
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/modal/ImageModal.js
  client/src/components/navbar/Navbar.js
  client/src/components/profile/EditProfilePage.js
  client/src/components/profile/EditProfilePage.test.js
  client/src/components/profile/Profile.js
  client/src/components/profile/Profile.test.js
  client/src/components/profile/ProfileButton.js
  client/src/components/profile/ProfileButton.test.js
  client/src/components/profile/ProfileForm.js
  client/src/components/profile/ProfileForm.test.js
  client/src/components/profile/ProfileUser.js
  client/src/index.css
  client/src/index.js
  client/src/reportWebVitals.js
  client/src/store/features/users/usersSlice.js
  client/src/styles/Footer.module.css
  client/src/styles/ImageModal.module.css
  client/src/styles/Profile-styles/EditProfile.module.css
  client/src/styles/Profile-styles/Profile.module.css
  client/src/styles/Profile-styles/ProfileButton.module.css
  client/src/styles/Profile-styles/ProfileUser.module.css
  client/src/styles/Profile-styles/Profileform.module.css
  client/yarn.lock
Labels: enhancement, task, must_have, user_story

#115 Feature/chats
  client/.eslintrc
  client/package-lock.json
  client/package.json
  client/services/people.js
  client/src/components/button/Button.js
  client/src/components/button/StartAChatButton.js
  client/src/components/chats/Chats.js
  client/src/components/chats/FriendStartAChat.js
  client/src/components/chats/FriendsStartAChat.js
  client/src/components/chats/LatestChat.js
  client/src/components/chats/LatestChats.js
  client/src/components/chats/mock_messages.js
  client/src/components/container_heading/ContainerHeading.js
  client/src/components/modal/ModalStartAChat.js
  client/src/components/profile/ProfileButton.js
  client/src/index.css
  client/src/styles/Button.module.css
  client/src/styles/ContainerHeading.module.css
  client/src/styles/FriendsStartAChat.module.css
  client/src/styles/LatestChat.module.css
  client/src/styles/ModalStartAChat.module.css
  client/src/styles/Profile-styles/Profile.module.css
  client/src/styles/Profile-styles/ProfileButton.module.css
  client/src/styles/SearchBox.module.css
  client/src/utils/helper.js
  client/yarn.lock
  node_modules/.yarn-integrity
  yarn.lock
Labels: enhancement, must_have, user_story

#128 use useNavigate hook to redirect the page once the friend is chosen
  client/src/components/chats/Chats.js
Labels: enhancement, task, must_have

#119 Feature/user service
  client/services/userService.js
  client/services/userService.test.js
  client/src/utils/config.js
Labels: enhancement, task, must_have

#133 Fix for scrollbarr appearing on the laptop viewports with low height
  client/src/styles/Signup-styles/Signup.module.css
Labels: task

#132 Feature/add chatroom
  client/package-lock.json
  client/package.json
  client/src/components/button/NewPictureButton.js
  client/src/components/chatroom/ChatRoom.js
  client/src/components/chats/Chats.js
  client/src/components/chats/mock_messages.js
  client/src/components/message/Message.js
  client/src/components/message_body/MessageBody.js
  client/src/components/message_forms/MessageForms.js
  client/src/components/message_head/MessageHead.js
  client/src/components/messages/Messages.js
  client/src/components/modal/ImageModal.js
  client/src/components/modal/UploadPictureModal.js
  client/src/components/modal/UseCameraModal.js
  client/src/components/new_message_form/NewMessageForm.js
  client/src/components/profile/Profile.js
  client/src/components/profile/ProfileUser.js
  client/src/components/user/User.js
  client/src/icons/default-user-profile-image.png
  client/src/icons/img-file-placeholder.png
  client/src/index.css
  client/src/services/messages.js
  client/src/services/people.js
  client/src/services/userService.js
  client/src/services/userService.test.js
  client/src/store/features/messages/messagesSlice.js
  client/src/store/features/users/usersSlice.js
  client/src/store/store.js
  client/src/styles/Button.module.css
  client/src/styles/ChatRoom-styles/ChatRoom.module.css
  client/src/styles/ChatRoom-styles/MessageForms.module.css
  client/src/styles/ChatRoom-styles/Messages.module.css
  client/src/styles/ImageModal.module.css
  client/src/styles/Navbar.module.css
  client/src/styles/Profile-styles/Profile.module.css
  client/src/styles/Profile-styles/ProfileUser.module.css
  client/src/styles/User.module.css
  client/src/utils/config.js
  client/src/utils/helper.js
  client/yarn.lock
  server/Controller/messageController.js
  server/package-lock.json
  server/package.json
  server/routes/messageRouter.js
  server/yarn.lock
Labels: task, must_have, feature

#137 replace name for email in the login mode
  client/src/components/signup/SignupForm.js
Labels: enhancement, task
